/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import conexion.Index;
import conexion.Servicio_factura;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author OSCARPC
 */
public class Gui_Factura extends javax.swing.JInternalFrame {
   Servicio_factura s;
        Index i;
    /**
     * Creates new form Gui_Factura1
     */
    public Gui_Factura() {
        initComponents();
        s = new Servicio_factura();
        i = new Index();
        Index.Imagen imagen = i.new Imagen();
        jPanel1.add(imagen);
        jPanel1.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtnota = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fechacrote = new datechooser.beans.DateChooserCombo();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        periodo_inicial = new datechooser.beans.DateChooserCombo();
        periodo_final = new datechooser.beans.DateChooserCombo();
        jLabel4 = new javax.swing.JLabel();
        fechapago = new datechooser.beans.DateChooserCombo();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Guardar");

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 3, 21)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FECHAS DE  FACTURACIÓN");

        txtnota.setColumns(20);
        txtnota.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        txtnota.setLineWrap(true);
        txtnota.setRows(5);
        txtnota.setTabSize(5);
        txtnota.setText("Con el no pago de dos facturas se suspenderá el servicio y se le cobrara el valor de la reconexión en el mes siguiente, si esta factura no es cancelada en las fechas indicadas, la junta tomara las medidas del caso y se incluirá el valor en el siguiente facturación. Esta factura no será valida sin el sello de cancelado o reporte de pago. En caso de no recibirse o extraviarse la factura solicite un duplicado ya que lo anterior no lo exime ");
        txtnota.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(txtnota);

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NOTA ");

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Maximo 500 letras incluyendo espacios");

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FECHA DE PAGO");

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FECHA DE SUSPENCIÓN");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PERIODOS DE FACTURACIÓN");

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INICIAL");

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FINAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(periodo_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(periodo_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(fechacrote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(fechapago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(211, 211, 211))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(periodo_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fechapago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechacrote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(periodo_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String []inci = periodo_inicial.getText().split("/");
        String []fin = periodo_final.getText().split("/");
        String []pago = fechapago.getText().split("/");
        String []corte = fechacrote.getText().split("/");

        //---------------------------------------------
        String Dia1, Mes1, Ano1;
        Dia1="";
        Mes1="";
        Ano1="";

        Dia1=inci[0] ;
        Mes1=inci[1] ;
        Ano1=inci[2] ;

        String Fechainci= "20"+Ano1+"/" + Mes1 + "/"+ Dia1;
        String Fechainci1= "20"+Ano1+"-" + Mes1 + "-"+ Dia1;

        //------------------------------------------------------------
        String Dia2, Mes2, Ano2;
        Dia2="";
        Mes2="";
        Ano2="";

        Dia2=fin[0] ;
        Mes2=fin[1] ;
        Ano2=fin[2] ;

        String Fechafin= "20"+Ano2+"/" + Mes2 + "/"+ Dia2;
        String Fechafin1= "20"+Ano2+"-" + Mes2 + "-"+ Dia2;
        //-----------------------------------------------------------------
        String Dia3, Mes3, Ano3;
        Dia3="";
        Mes3="";
        Ano3="";

        Dia3=pago[0] ;
        Mes3=pago[1] ;
        Ano3=pago[2] ;

        String Fechapago= "20"+Ano3+"/" + Mes3 + "/"+ Dia3;
        String Fechapago1= "20"+Ano3+"-" + Mes3 + "-"+ Dia3;
        //-----------------------------------------------------------------
        String Dia4, Mes4, Ano4;
        Dia4="";
        Mes4="";
        Ano4="";

        Dia4=corte[0] ;
        Mes4=corte[1] ;
        Ano4=corte[2] ;

        String Fechacorte= "20"+Ano4+"/" + Mes4 + "/"+ Dia4;
        String Fechacorte1= "20"+Ano4+"-" + Mes4 + "-"+ Dia4;
        String Nota = txtnota.getText();

        String Resultado = s.compararFechasConDate(Fechainci, Fechafin, Fechacorte, Fechapago);

        String cadena =txtnota.getText();
        char[] arrayChar = cadena.toCharArray();
        String VerPeriodo = s.VerificarPeriodo(Fechainci1, Fechafin1, Fechacorte1, Fechapago1);

        if (VerPeriodo.equals("1")){

            JOptionPane.showMessageDialog(new JDialog(), "El periodo de Facturación ya Existe");

        }else if (periodo_inicial.getText().equals(periodo_final.getText())||
            periodo_inicial.getText().equals(fechacrote.getText()) ||
            fechapago.getText().equals(fechacrote.getText()) ||
            fechapago.getText().equals(periodo_final.getText()) ||
            periodo_final.getText().equals(fechacrote.getText()) ||
            periodo_final.getText().equals(fechapago.getText())
        ){

            JOptionPane.showMessageDialog(new JDialog(), "Las Fechas no pueden ser iguales  ");
        }else if(arrayChar.length > 500){
            JOptionPane.showMessageDialog(new JDialog(), "La nota asiciada a la factura debe tener menos de 500 letras N° LETRAS: "+arrayChar.length);
        }else if(txtnota.getText().equals("")){

            JOptionPane.showMessageDialog(new JDialog(), "La nota no puede estar vacia ");

        }
        else if (Resultado.equals("")){

            s.GenerarFacturacion(Fechainci, Fechafin, Fechapago, Fechacorte, Nota);    // TODO add your handling code here:
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo fechacrote;
    private datechooser.beans.DateChooserCombo fechapago;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private datechooser.beans.DateChooserCombo periodo_final;
    private datechooser.beans.DateChooserCombo periodo_inicial;
    private javax.swing.JTextArea txtnota;
    // End of variables declaration//GEN-END:variables
}
