/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import conexion.ConexionMysql;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.InputStreamReader;

import java.sql.ResultSet;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;



/**
 *
 * @author OSCARPC
 */
public final class Gui_Backup extends javax.swing.JInternalFrame {


    /**
     * Creates new form Gui_Backup1
     */
    public Gui_Backup() {
        initComponents();
         GenerarBackupMySQL(); 
        // conm = new ConexionMysql();
    }
    
       public String ConsulRuta (){
     
            ConexionMysql conm = new ConexionMysql();
           String ruta_back = "";
           try {    
                           
            ResultSet res = null;
            PreparedStatement pstm = (PreparedStatement) conm.getConnection().prepareStatement( 
                    "SELECT ruta_back FROM  fechas_facturacion");

            res = (ResultSet) pstm.executeQuery();
            while(res.next()){
                ruta_back = res.getString("ruta_back");
               
            }
            res.close();
           
     }
     catch(SQLException e){
     System.out.println(e);
     }
  
     return ruta_back;
     }
    
void GenerarBackupMySQL(){
   
     String ruta = ConsulRuta();
    //String ruta = "C:\\wamp\\bin\\mysql\\mysql5.6.17\\bin\\";
       
     
        java.util.Date fecha = new Date();
        System.out.println (fecha);
        DateFormat fechaHora = new SimpleDateFormat("dd-MMMM-yyyy");
		String convertido = fechaHora.format(fecha);
		
        int resp;
        resp=RealizarBackupMySQL.showSaveDialog(this);//JFileChooser de nombre RealizarBackupMySQL
        if (resp==JFileChooser.APPROVE_OPTION) {//Si el usuario presiona aceptar; se genera el Backup
            try{
                Runtime runtime = Runtime.getRuntime();
                File backupFile = new File(String.valueOf(RealizarBackupMySQL.getSelectedFile().toString())+" "+convertido+".sql");
                FileWriter fw = new FileWriter(backupFile);
                Process child = runtime.exec(ruta+"mysqldump --opt --password=admintotumo --user=root --databases data_a_c_p_t");
                InputStreamReader irs = new InputStreamReader(child.getInputStream());
                BufferedReader br = new BufferedReader(irs);
                String line;
                while( (line=br.readLine()) != null ) {
                    fw.write(line + "\n");
                }
                fw.close();
                irs.close();
                br.close();
                JOptionPane.showMessageDialog(null, "Archivo generado","Verificar",JOptionPane. INFORMATION_MESSAGE);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error no se genero el archivo por el siguiente motivo:"+e.getMessage(), "Verificar",JOptionPane.ERROR_MESSAGE);
            }
            //JOptionPane.showMessageDialog(null, "Archivogenerado","Verificar",JOptionPane.INFORMATION_MESSAGE);
        } else if (resp==JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null,"Ha sido cancelada la generacion del Backup");
        }
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RealizarBackupMySQL = new javax.swing.JFileChooser();

        setClosable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(124, 188, 248));

        RealizarBackupMySQL.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        RealizarBackupMySQL.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        RealizarBackupMySQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarBackupMySQLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RealizarBackupMySQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RealizarBackupMySQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RealizarBackupMySQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarBackupMySQLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RealizarBackupMySQLActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser RealizarBackupMySQL;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
