/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Gui_inmueble.java
 *
 * Created on 18/06/2013, 11:46:33 AM
 */
package vista;

import conexion.ConexionMysql;
import conexion.Index;
import conexion.Servicio_cliente;
import conexion.Servicio_inmueble;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import modelo.Inmueble;

/**
 *
 * @author Paolita
 */
public class Gui_inmueble extends javax.swing.JInternalFrame {
    private final javax.swing.DefaultComboBoxModel modelocbAlcantarillado;
    private final javax.swing.DefaultComboBoxModel modelocbAcueducto;
    Servicio_inmueble s = new Servicio_inmueble();
    Servicio_cliente c = new Servicio_cliente();
    ConexionMysql conm = new ConexionMysql();
    Index i = new Index();
    Object[][] datos;
    Object[][] datos1;
    Object[][] datos2;

    String cantidad = "";
    String CodInmu2 = "";

      
    /** Creates new form Gui_inmueble */
    public Gui_inmueble() {
          modelocbAlcantarillado = new javax.swing.DefaultComboBoxModel(new String[] {});
          modelocbAcueducto = new javax.swing.DefaultComboBoxModel(new String[] {});
        initComponents();
        s = new Servicio_inmueble();
       // centrarVentana();
        int numero=0;
        datos1=s.NumeroGestion(numero);
         String num=(String.valueOf(datos1[0][0]));
        if (num.equals("null")){
        labelCodigo.setText("1");
        }else {
        labelCodigo.setText(String.valueOf(datos1[0][0]));
        }
        //Fondo panel
        i = new Index();
        Index.Imagen imagen = i.new Imagen();
        jPanel1.add(imagen);
        jPanel1.repaint();
        ComboAlcantarillado();
        ComboAcueducto();
      
       
       
        
    }
     public void centrarVentana() {
                // Se obtienen las dimensiones en pixels de la pantalla.
                Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
                // Se obtienen las dimensiones en pixels de la ventana.
                Dimension ventana = getSize();
                // Una cuenta para situar la ventana en el centro de la pantalla.

                setLocation((pantalla.width - ventana.width) / 2 ,0);
 }
    private void ComboAlcantarillado() {
         int i = 0;
        int j = 0;
        modelocbAlcantarillado.addElement("Elije un Servicio");
        datos=s.ComboAlcantarillado();
        for (i=1 ; i <= datos.length ;i=i+1){
        
        modelocbAlcantarillado.addElement(datos[j][1]);    
        
        j++;
        }
              
    }
    
    private void ComboAcueducto() {
        int i = 0;
        int j = 0;
        modelocbAcueducto.addElement("Elije un Servicio");
        datos=s.ComboAcueducto();
        for (i=1 ; i <= datos.length ;i=i+1){
        
        modelocbAcueducto.addElement(datos[j][1]);    
        
        j++;
        }
           
    }
    
    public Inmueble armainmueble(){
          Inmueble inmueble = null;
          String documento = txtDocumento.getText().trim();
          String codigo =labelCodigo.getText().trim();
          String direccion = txtDireccion.getText().trim();
          String telefono = txtTelefono.getText().trim();          
          String NomAlcantarillado= cbAlcantarillado.getSelectedItem().toString();
          String NomAcueducto= cbAcueducto.getSelectedItem().toString();
          
          if(direccion.equals("")){
               JOptionPane.showMessageDialog(new JDialog(), "La Direccion no puede ser vacia");
               }else if(telefono.matches("[a-z]*")){
                   JOptionPane.showMessageDialog(new JDialog(), "El telefono debe ser numerico");
                 }else if(NomAlcantarillado.equals("Elije un Servicio")){
                      JOptionPane.showMessageDialog(new JDialog(), "Debe seleccionar el alcantarillado");
                     }else if(NomAcueducto.equals("Elije un Servicio")){
                          JOptionPane.showMessageDialog(new JDialog(), "Debe seleccionar el Acueducto");
                     } else if(documento.equals("")){
                          JOptionPane.showMessageDialog(new JDialog(), "Debe indicar el Documento del titular");
                     }else if(codigo.equals("")){
                          JOptionPane.showMessageDialog(new JDialog(), "Debe indicar el codigo del inmueble");
                     }else{
                     
                     
                     inmueble = new Inmueble(codigo, direccion,telefono, NomAlcantarillado, documento, NomAcueducto);
                     }
          return inmueble;
        
        
          
                     
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbAcueducto = new javax.swing.JComboBox();
        cbAlcantarillado = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        labelCodigo.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");

        txtNombre.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        txtNombre.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Documento del Titular ");

        txtDocumento.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direccion");

        txtDireccion.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefono");

        txtTelefono.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Alcantarillado");

        jLabel14.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Acueducto");

        cbAcueducto.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        cbAcueducto.setModel(modelocbAcueducto);

        cbAlcantarillado.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        cbAlcantarillado.setModel(modelocbAlcantarillado);
        cbAlcantarillado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlcantarilladoActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cliente1.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar12.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultar1.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar1.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar1.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar1.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel16)))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel17)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel18)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel19))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDocumento)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtTelefono)
                                    .addComponent(cbAlcantarillado, 0, 196, Short.MAX_VALUE)
                                    .addComponent(cbAcueducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addGap(18, 18, 18)
                .addComponent(labelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(labelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAlcantarillado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbAcueducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtDocumentoActionPerformed

    private void cbAlcantarilladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlcantarilladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAlcantarilladoActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        String documento = txtDocumento.getText().trim();
 if(documento.equals("")){
      JOptionPane.showMessageDialog(new JDialog(), "Digite el numero del documento");
                                                     
 }else{
   datos= c.ConsultarCliente(documento);
   String nombre = "";
   nombre = String.valueOf(datos[0][3]);
   if (nombre.equals("null")){
   JOptionPane.showMessageDialog(new JDialog(), "No se encuentro la persona");
   } else {
   txtNombre.setText(String.valueOf(datos[0][3]));
   }
    
 }
        
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
         Inmueble inmueble = null;
         inmueble = armainmueble();
         if(inmueble == null){}else{
         s.insertar(inmueble);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        if (labelCodigo.getText().equals("")){
    
       JOptionPane.showMessageDialog(new JDialog(), "Debe digitar el Codigo del Inmueble");
    }else{
    
        String DOCUMENTO = labelCodigo.getText();

        datos=s.ConsultarInmueble(DOCUMENTO);
        CodInmu2 = String.valueOf(datos[0][3]);
        txtDireccion.setText(String.valueOf(datos[0][1]));
        txtDocumento.setText(String.valueOf(datos[0][3]));
        String documento=String.valueOf(datos[0][3]);
        datos2= c.ConsultarCliente(documento);
         String nombre = "";
         nombre = String.valueOf(datos2[0][3]);
            if (nombre.equals("null")){
                 JOptionPane.showMessageDialog(new JDialog(), "No se encuentro el inmueble");
            } else {
                txtNombre.setText(String.valueOf(datos2[0][3]));
   }
 //txtNombre.setText(String.valueOf(datos[0][1]));  
    txtTelefono.setText(String.valueOf(datos[0][2])); 
    String alcantarillado=(String.valueOf(datos[0][5]));
    String Acueducto=(String.valueOf(datos[0][8]));
    System.out.println(alcantarillado + "/////");
    System.out.println(Acueducto + "/////");
    cbAlcantarillado.setSelectedItem(alcantarillado);
    cbAcueducto.setSelectedItem(Acueducto);
     }    
  
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        String documento = labelCodigo.getText();
    
    
    if (txtDireccion.getText().equals("") || txtTelefono.getText().equals("") ||
        cbAlcantarillado.getSelectedItem().toString().equals("Elije un Servicio") ||
        cbAcueducto.getSelectedItem().toString().equals("Elije un Servicio") || documento.equals("")){

    JOptionPane.showMessageDialog(new JDialog(), "TODOS LOS CAMPOS SON OBLIGATORIOS");

    }else{
        Inmueble inmueble = null;
        inmueble = armainmueble();
            if(inmueble == null){}else{
            s.ModificarInmueble(inmueble);
       
            s.insertarcambiousuario(inmueble,CodInmu2 );
        }
    }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        String Codigo = labelCodigo.getText();
         s.BorrarInmueble(Codigo);    
    
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        datos1 = s.ConsultarInmuebleFactura();   
        int tamaño = datos1.length;
//JOptionPane.showMessageDialog(new JDialog(), "tamaño"+tamaño);
        int numero=0;
        datos1=s.NumeroGestion(numero);
          labelCodigo.setText(String.valueOf(datos1[0][0]));
    
        txtNombre.setText("");
        txtDireccion.setText("");
        txtDocumento.setText("");
        txtTelefono.setText("");
        cbAlcantarillado.setSelectedItem("Elije un Servicio");
        cbAcueducto.setSelectedItem("Elije un Servicio");
    }//GEN-LAST:event_jLabel19MouseClicked

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbAcueducto;
    private javax.swing.JComboBox cbAlcantarillado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField labelCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
